### ISSUE TITLE
A question about ImageNet291 dataset.

### ISSUE THREAD

**Issue by zhanjiahui** [williamyang1991/GP-UNIT#4]
Thank you for your excellent work.

Based on your paper, it seems that during training, the first stage used paired data constructed by BigGAN and the second stage used unpaired data.

The first stage uses two datasets, SynImageNet291 and ImageNet291. And SynImageNet291 does not appear to contain face images.

ImageNet291 contains images from ImageNet and Celeba-HQ. **In data_preparation.md you provide a way to detect objects of the same class in ImageNet (extract features using VGG and sort them, then use object detection algorithm to crop), but it doesn't seem to provide a way to build corresponding relations among different domains. How do you build  relations among different domains?**

**I looked at data_preparation.md for a long time, but still feel confused. Because ImageNet291 contains the face image. How do you establish the correspondence between Celeba-HQ images and other domain images?**

**Comment by williamyang1991** [comment]
We learn correspondence between 291 domains with SynImageNet291.
We don't learn the correspondence between Celeba-HQ images and other domain images with supervision.
You know, BigGAN is not trained with paired data but it still presents correspondences between similar domains.
Therefore, we assume the encoder is also able to learn some correspondence between Celeba-HQ images and related domains like animal faces unsupervisedly.

**Comment by zhanjiahui** [comment]
Thank you for your quick answer! I see!
