### ISSUE TITLE
custom training

### ISSUE THREAD

**Issue by Akansel-AKYOL** [williamyang1991/GP-UNIT#5]
Is it possible to custom training with custom data? I created the data structure but I don't know what should be initially in the checkpoint folder? And what is other requirements?

**Comment by williamyang1991** [comment]
If you want to train the encoder with your costom data, you may refer to this [structure](https://github.com/williamyang1991/GP-UNIT/tree/main/data_preparation)

If you want to train the I2I network with our pre-trained encoder, you can use any folder structure, but specify the paths to your costom  data by: 
### Train Image-to-Image Transaltion Network
```python
python train.py --task TASK --batch BATCH_SIZE --iter ITERATIONS \
                --source_paths SPATH1 SPATH2 ... SPATHS --source_num SNUM1 SNUM2 ... SNUMS \
                --target_paths TPATH1 TPATH2 ... TPATHT --target_num TNUM1 TNUM2 ... TNUMT
```
where `SPATH1`~`SPATHS` are paths to `S` folders containing images from the source domain (*e.g.*, `S` classes of ImageNet birds),
`SNUMi` is the number of images in `SPATHi` used for training. 
`TPATHi`, `TNUMi` are similarily defined but for the target domain. 
By default, `BATCH_SIZE=16` and `ITERATIONS=75000`.
If `--source_num`/`--target_num` is not specified, all images in the folders are used.
