### ISSUE TITLE
How to train 

### ISSUE THREAD

**Issue by dvlyuying** [williamyang1991/GP-UNIT#6]
Dear authors:
I want to ask about the training of dog2bird.
Which kind of dog in ImageNet291 needs to be used?  There are many dog files from 151_dog to 168_dog in this ImageNet291 data set. Can you tell me more details about the training of dog2bird?
Looking forward to your early reply!

**Comment by williamyang1991** [comment]
we use four classes of dogs with class index: 214, 218, 222, 232

**Comment by 761370085** [comment]
你的机器视觉论文写作课作业已收到，有问题可以联系我，祝好！

**Comment by dvlyuying** [comment]
Thank you so much!

**Comment by dvlyuying** [comment]
你的机器视觉论文写作课作业已收到，有问题可以联系我，祝好！
