### ISSUE TITLE
A question in Stage 2

### ISSUE THREAD

**Issue by zjwulbx** [williamyang1991/GP-UNIT#9]
Hello, I have a question in Stage2. When we calculate the Lsty in stage2, why we use the style encoder in decoder rather than the style encoder in generator? Why do we not use the same style encoder when generating images and calculating Lsty.

**Comment by williamyang1991** [comment]
I think either is OK.
In existing researches, MUNIT uses style encoder in generator, FUNIT/COCO-FUNIT use style encoder in discriminator (D is not decoder in our paper. D is discriminator).
We just follow the setting of FUNIT/COCO-FUNIT.

MUNIT: 2018 ECCV Multimodal Unsupervised Image-to-Image Translation
FUNIT: 2019 ICCV Few-Shot Unsupervised Image-to-Image Translation
COCO-FUNIT: 2020 ECCV COCO-FUNIT: Few-Shot Unsupervised Image Translation with a Content Conditioned Style Encoder

**Comment by zjwulbx** [comment]
thank you for your answer. sorry , D indeed is the discriminator, what I want to express in my mind is discriminator. But I made a mistake to write the word  ,sorry~ I am just a bit of curious why the style encoder is different when calculating Lsty after generating the imgs. Thank you very much~
